#!/bin/bash
yum update -ysudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.reposudo yum -y install terraform
sudo yum -y install terraform
terraform --version
